experiment:
  name: "/Shared/{{cookiecutter.project_name}}"
  tracking_uri: "sqlite:///mlruns.db"
  artifact_location: "./mlruns"

model_registry:
  # Specifies the name of the Registered Model to use when registering a trained model to
  # the MLflow Model Registry
  model_name: {%raw-%}{{{%endraw%}MODEL_NAME|default('{{cookiecutter.project_name}}_model'){%raw-%}}}{%endraw%}

# Override the default train / validation / test dataset split ratios
SPLIT_RATIOS: [0.80, 0.10, 0.10]

INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#ingest-step
  # TODO: Specify the format of the dataset
  using: parquet
  # TODO: update this field to point to a local filesystem path containing e.g. a sample of your model training
  # dataset for local development.
  location: "./data/sample.parquet"
  loader_method: load_file_as_dataframe

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#batch-scoring
  # Use a larger section of the TLC Trip Record Dataset for the batch scoring feature
  # Specify the format of the dataset
  using: parquet
  # TODO: update this field to point to a local filesystem path containing e.g. a sample of your input dataset
  # for batch inference
  location: "./data/sample.parquet"
  loader_method: load_file_as_dataframe

PREDICT_OUTPUT_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#predict-step
  # Specify the output format of the batch scoring predict step
  using: parquet
  # Specify the output location of the batch scoring predict step
  location: "./data/sample_output.parquet"
