# This Azure DevOps Pipeline tests and validates Terraform config (ML resource config and more)
# defined under databricks-config, upon creating a PR against the default branch.
# The pipeline then deploys Terraform resources (ML resource config and more)
# defined under databricks-config, when a PR has been successfully merged into the default branch

trigger:
  branches:
    include:
      - {{cookiecutter.default_branch}}
  paths:
    include:
      - databricks-config/**

variables:
  working-directory: ./databricks-config
  ARM_SUBSCRIPTION_ID: $(armSubscriptionId)

stages:

# Run Terraform CI stage on pull requests to {{cookiecutter.default_branch}}
- stage: TerraformCI
  displayName: 'Terraform Tests for {{cookiecutter.project_name}}'
  # Trigger TerraformCI stage on PR against the default branch, and not on pushes to other branches
  condition: |
    and(
      not(eq(variables['Build.Reason'], 'IndividualCI')),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/{{cookiecutter.default_branch}}')
    )

  jobs:
  - job: StagingTerraformCI
    displayName: 'Continuous integration tests for staging Terraform scripts'

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      environment: staging

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    - script: |
        set -e
        stagingAzureSpTenantId=$(stagingAzureSpTenantId)
        stagingAzureSpApplicationId=$(stagingAzureSpApplicationId)
        stagingAzureSpClientSecret=$(stagingAzureSpClientSecret)
        DATABRICKS_TOKEN=$(.azure/devops-pipelines/scripts/generate-aad-token.sh "$stagingAzureSpTenantId" "$stagingAzureSpApplicationId" "$stagingAzureSpClientSecret")
        echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]${DATABRICKS_TOKEN}"
      displayName: 'Configure AAD auth'

    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
      displayName: 'Install Terraform'

    - script: |
       terraform fmt -check -recursive -diff
      displayName: 'Terraform fmt'
      continueOnError: true

    - script: |
        echo "working-directory: $(working-directory)/$(environment)"
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)

    - script: |
        terraform validate -no-color
      displayName: 'Terraform Validate'
      workingDirectory: $(working-directory)/$(environment)

    - script: |
        terraform plan -no-color \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Plan'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)
        DATABRICKS_HOST: $(stagingDatabricksHost)

  - job: ProdTerraformCI
    displayName: 'Continuous integration tests for prod Terraform scripts'
    dependsOn: []   # Removes the implicit dependency on previous job and force ProdTerraformCI job to run in parallel

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      environment: prod

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    - script: |
        set -e
        prodAzureSpTenantId=$(prodAzureSpTenantId)
        prodAzureSpApplicationId=$(prodAzureSpApplicationId)
        prodAzureSpClientSecret=$(prodAzureSpClientSecret)
        DATABRICKS_TOKEN=$(.azure/devops-pipelines/scripts/generate-aad-token.sh "$prodAzureSpTenantId" "$prodAzureSpApplicationId" "$prodAzureSpClientSecret")
        echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]${DATABRICKS_TOKEN}"
      displayName: 'Configure AAD auth'

    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
      displayName: 'Install Terraform'

    - script: |
       terraform fmt -check -recursive -diff
      continueOnError: true
      displayName: 'Terraform fmt'

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)

    - script: |
        terraform validate -no-color
      displayName: 'Terraform Validate'
      workingDirectory: $(working-directory)/$(environment)

    - script: |
        terraform plan -no-color \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Plan'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)
        DATABRICKS_HOST: $(prodDatabricksHost)

# Run Terraform CD stage after successfully merging to {{cookiecutter.default_branch}}
- stage: TerraformCD
  displayName: 'Terraform Deployment for {{cookiecutter.project_name}}'
  # Trigger TerraformCD after successfully pushing to the default branch, not on initial PR to the default branch
  condition: |
    and(
      eq(variables['Build.SourceBranch'], 'refs/heads/{{cookiecutter.default_branch}}'),
      not(eq(variables['Build.Reason'], 'PullRequest'))
    )

  jobs:
  - job: StagingTerraformCD
    displayName: 'Continuous deployment for staging Terraform resources'

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      environment: staging

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    - script: |
        set -e
        stagingAzureSpTenantId=$(stagingAzureSpTenantId)
        stagingAzureSpApplicationId=$(stagingAzureSpApplicationId)
        stagingAzureSpClientSecret=$(stagingAzureSpClientSecret)
        DATABRICKS_TOKEN=$(.azure/devops-pipelines/scripts/generate-aad-token.sh "$stagingAzureSpTenantId" "$stagingAzureSpApplicationId" "$stagingAzureSpClientSecret")
        echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]${DATABRICKS_TOKEN}"
      displayName: 'Configure AAD auth'

    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
      displayName: 'Install Terraform'

    - script: |
       terraform fmt -check
      displayName: 'Terraform fmt'
      continueOnError: true

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)

    - script: |
        terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: $(working-directory)/$(environment)

    - script: |
        terraform plan -no-color \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Plan'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)
        DATABRICKS_HOST: $(stagingDatabricksHost)

    - script: |
        terraform apply -auto-approve \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Apply'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)
        DATABRICKS_HOST: $(stagingDatabricksHost)

    - script: |
        TERRAFORM_OUTPUT=$(terraform -chdir=staging output -json)
        mkdir -p output
        echo $TERRAFORM_OUTPUT | jq '.' > output/$(environment).json
      displayName: 'Terraform Output'
      workingDirectory: $(working-directory)
      env:
        ARM_TENANT_ID: $(stagingAzureSpTenantId)
        ARM_CLIENT_ID: $(stagingAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(stagingAzureSpClientSecret)

    - script: |
        ORIGINAL_BRANCH='$(Build.SourceBranch)'
        ROOT=refs/heads/
        BRANCH="${ORIGINAL_BRANCH/$ROOT/''}"
        git checkout -b $BRANCH
        git config --global user.name "Terraform Output Azure DevOps Pipeline"
        git config --global user.email "<>"
        output=$(git status --porcelain)
        if [ -n "$output" ]
        then
          git add -A
          git commit -m "Commit staging output"
          git push --set-upstream origin $BRANCH
          {%- if cookiecutter.default_branch != cookiecutter.release_branch %}
          git fetch origin {{cookiecutter.release_branch}}
          git checkout {{cookiecutter.release_branch}}
          git cherry-pick {{cookiecutter.default_branch}}
          git push
          {%- endif %}
        fi
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: 'Commit Terraform Output to File'

  - job: ProdTerraformCD
    displayName: 'Continuous deployment for staging Terraform resources'

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      environment: prod

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    - script: |
        set -e
        prodAzureSpTenantId=$(prodAzureSpTenantId)
        prodAzureSpApplicationId=$(prodAzureSpApplicationId)
        prodAzureSpClientSecret=$(prodAzureSpClientSecret)
        DATABRICKS_TOKEN=$(.azure/devops-pipelines/scripts/generate-aad-token.sh "$prodAzureSpTenantId" "$prodAzureSpApplicationId" "$prodAzureSpClientSecret")
        echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]${DATABRICKS_TOKEN}"
      displayName: 'Configure AAD auth'

    - script: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
      displayName: 'Install Terraform'

    - script: |
       terraform fmt -check
      displayName: 'Terraform fmt'
      continueOnError: true

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)

    - script: |
        terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: $(working-directory)/$(environment)

    - script: |
        terraform plan -no-color \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Plan'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)
        DATABRICKS_HOST: $(prodDatabricksHost)

    - script: |
        terraform apply -auto-approve \
        -var="git_repo_url=$(Build.Repository.Uri)"
      displayName: 'Terraform Apply'
      workingDirectory: $(working-directory)/$(environment)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)
        DATABRICKS_HOST: $(prodDatabricksHost)

    - script: |
        TERRAFORM_OUTPUT=$(terraform -chdir=prod output -json)
        mkdir -p output
        echo $TERRAFORM_OUTPUT | jq '.' > output/$(environment).json
      displayName: 'Terraform Output'
      workingDirectory: $(working-directory)
      env:
        ARM_TENANT_ID: $(prodAzureSpTenantId)
        ARM_CLIENT_ID: $(prodAzureSpApplicationId)
        ARM_CLIENT_SECRET: $(prodAzureSpClientSecret)

    - script: |
        ORIGINAL_BRANCH='$(Build.SourceBranch)'
        ROOT=refs/heads/
        BRANCH="${ORIGINAL_BRANCH/$ROOT/''}"
        git checkout -b $BRANCH
        git config --global user.name "Terraform Output Azure DevOps Pipeline"
        git config --global user.email "<>"
        output=$(git status --porcelain)
        if [ -n "$output" ]
        then
          git add -A
          git commit -m "Commit prod output"
          git push --set-upstream origin $BRANCH
          {%- if cookiecutter.default_branch != cookiecutter.release_branch %}
          git fetch origin {{cookiecutter.release_branch}}
          git checkout {{cookiecutter.release_branch}}
          git cherry-pick {{cookiecutter.default_branch}}
          git push
          {%- endif %}
        fi
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: 'Commit Terraform Output to File'
