# This Azure Pipeline runs unit and integration tests.
# This pipeline is triggered upon making a PR against the {{cookiecutter.default_branch}} branch.
# Unit tests are defined under {{cookiecutter.project_name_alphanumeric_underscore}}/tests
# and are executed on the Azure Pipelines agent.
# The integration test deploys and runs the model_training_job defined in {{cookiecutter.project_name_alphanumeric_underscore}}/databricks-resource/model-workflow-resource.yml
# This integration test is run in the staging workspace, as defined under {{cookiecutter.project_name_alphanumeric_underscore}}/bundle.yml

trigger:
  branches:
    include:
      - {{cookiecutter.default_branch}} 

variables:
  - group: {{cookiecutter.project_name}} variable group
  - name: DATABRICKS_CLI_VERSION
    value: 0.100.2

jobs:
  - job: UnitTests
    displayName: 'Unit Tests'
    # Trigger unit test upon making a PR against the {{cookiecutter.default_branch}} branch
    condition: |
      and(
        not(eq(variables['Build.Reason'], 'IndividualCI')),
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/{{cookiecutter.default_branch}}')
      )
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8

    - script: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r {{cookiecutter.project_name_alphanumeric_underscore}}/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pytest --junitxml=test-unit.xml
      displayName: 'Run unit tests with pytest'

  - job: IntegrationTests
    displayName: 'Integration Tests'
    # Integration tests will only run upon unit tests successfully passing
    dependsOn: UnitTests
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest' 

    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    # Install Databricks CLI
    - task: Bash@3
      inputs:        
        targetType: 'filePath'
        filePath: '.azure/devops-pipelines/scripts/setup-databricks-cli.sh'
      env:
        VERSION: $(DATABRICKS_CLI_VERSION)
        AGENT_OS: 'Linux'
        AGENT_ARCHITECTURE: 'X64'
      displayName: 'Install Databricks CLI'          

    # Extract Databricks version to test installation
    - script: |
        databricks version --detail | jq .
      displayName: 'Get Databricks CLI version'

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle validate -e test  
      workingDirectory: {{cookiecutter.project_name_alphanumeric_underscore}}
      displayName: Validate bundle for test environment in staging workspace 
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)

    # Deploy bundle to staging workspace
    - script: |
        databricks bundle deploy -e test
      workingDirectory: {{cookiecutter.project_name_alphanumeric_underscore}}
      displayName: Deploy bundle to test environment in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)          

    # Run model_training_job defined in bundle in the staging workspace
    - script: |
        databricks bundle run model_training_job -e test
      workingDirectory: {{cookiecutter.project_name_alphanumeric_underscore}}
      displayName: Run training workflow for test environment in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)          